[variables]
main_domain = "${domain}"
POSTGRES_DB = "keycloak"
POSTGRES_USER = "keycloakuser"
POSTGRES_PASSWORD = "${password:32}"
KEYCLOAK_ADMIN = "admin"
KEYCLOAK_ADMIN_PASSWORD = "${password:32}"
KC_HOSTNAME = "${main_domain}"

[config]
[[config.domains]]
serviceName = "keycloak"
port = 8080
host = "${main_domain}"

[config.env]
POSTGRES_DB = "${POSTGRES_DB}"
POSTGRES_USER = "${POSTGRES_USER}"
POSTGRES_PASSWORD = "${POSTGRES_PASSWORD}"
KEYCLOAK_ADMIN = "${KEYCLOAK_ADMIN}"
KEYCLOAK_ADMIN_PASSWORD = "${KEYCLOAK_ADMIN_PASSWORD}"
KC_HOSTNAME = "${KC_HOSTNAME}"

[[config.mounts]]
