version: "3.8"

services:
  memos:
    image: neosmemo/memos:stable
    restart: unless-stopped
    volumes:
      - memos_data:/var/opt/memos
    environment:
      - MEMOS_MODE=${MEMOS_MODE}
      - MEMOS_PORT=${MEMOS_PORT}
    ports:
      - "5230"
volumes:
  memos_data:
