[variables]
main_domain = "${domain}"
ADMIN_PASSWORD = "${password:32}"
MAIL_USERNAME = "${username}"
MAIL_PASSWORD = "${password:32}"
SECRET_KEY = "${password:64}"

[config]
[[config.domains]]
serviceName = "ihatemoney"
port = 8000
host = "${main_domain}"

[config.env]
DEBUG = "False"
ACTIVATE_DEMO_PROJECT = "True"
ACTIVATE_ADMIN_DASHBOARD = "False"
ADMIN_PASSWORD = "${ADMIN_PASSWORD}" # used for admin access
ALLOW_PUBLIC_PROJECT_CREATION = "True"
BABEL_DEFAULT_TIMEZONE = "UTC"
GREENLET_TEST_CPP = "no"
MAIL_DEFAULT_SENDER = "Budget manager <admin@example.com>"
MAIL_PASSWORD = "${MAIL_PASSWORD}" # used for mail service auth
MAIL_PORT = "25"
MAIL_SERVER = "localhost"
MAIL_USE_SSL = "False"
MAIL_USE_TLS = "False"
MAIL_USERNAME = "${MAIL_USERNAME}" # used for mail service auth
SECRET_KEY = "${SECRET_KEY}" # used for session security
SESSION_COOKIE_SECURE = "True"
SHOW_ADMIN_EMAIL = "True"
SQLALCHEMY_DATABASE_URI = "sqlite:////database/ihatemoney.db"
SQLALCHEMY_TRACK_MODIFICATIONS = "False"
APPLICATION_ROOT = "/"
ENABLE_CAPTCHA = "False"
LEGAL_LINK = ""
PORT = "8000"
PUID = "0"
PGID = "0"

[[config.mounts]]
volumeName = "sqlite-db"
mountPath = "/database"
